// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdcttDuekgdC51UlLft3_c-6vC_YYYOo',
    appId: '1:535448206513:web:8eaafcaeb2a01dab3e3690',
    messagingSenderId: '535448206513',
    projectId: 'mobile-project-fall-2025',
    authDomain: 'mobile-project-fall-2025.firebaseapp.com',
    storageBucket: 'mobile-project-fall-2025.firebasestorage.app',
    measurementId: 'G-SKGCTT9NX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0iQSNX0Yvd89eYO80wVNTlHOnLJ3amv4',
    appId: '1:535448206513:android:2aaa8fef4d89c2603e3690',
    messagingSenderId: '535448206513',
    projectId: 'mobile-project-fall-2025',
    storageBucket: 'mobile-project-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3BXzdzZWbVuVtaRI_fsj4g-gZOss3C-U',
    appId: '1:535448206513:ios:63e3d555e4a364f03e3690',
    messagingSenderId: '535448206513',
    projectId: 'mobile-project-fall-2025',
    storageBucket: 'mobile-project-fall-2025.firebasestorage.app',
    iosBundleId: 'com.hediety.users',
  );

}