// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwnlF6OIoKzRov3G-9emlj_JAZUOLiMKo',
    appId: '1:84469258596:web:05edd06a30904953a9c271',
    messagingSenderId: '84469258596',
    projectId: 'hediety',
    authDomain: 'hediety.firebaseapp.com',
    storageBucket: 'hediety.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7PHoH0EduJs3Fv3NhYlBLbCjT4815A94',
    appId: '1:84469258596:android:b6c45f0f39f08216a9c271',
    messagingSenderId: '84469258596',
    projectId: 'hediety',
    storageBucket: 'hediety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbaaSvOv_GRjitkOEj1IXAGDsNEwRJnMw',
    appId: '1:84469258596:ios:5cf8be85b3798635a9c271',
    messagingSenderId: '84469258596',
    projectId: 'hediety',
    storageBucket: 'hediety.firebasestorage.app',
    iosBundleId: 'com.example.hediety',
  );
}
